# Generated by Django 2.2.1 on 2019-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
