# Generated by Django 2.2.1 on 2019-06-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190618_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='files',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
