# Generated by Django 2.2.1 on 2019-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190618_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
