# Generated by Django 2.2.1 on 2019-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190618_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
