# Generated by Django 2.2.1 on 2019-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190618_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(default='https://en.wikipedia.org/wiki/Rickrolling'),
        ),
    ]
